"""Bitbucket MCP Server - Container optimized MCP server for Bitbucket API"""

try:
    from importlib.metadata import version, PackageNotFoundError
    __version__ = version("bitbucket-mcp-py")
except PackageNotFoundError:
    try:
        from ._version import __version__  # Generated by hatch-vcs at build time
    except ImportError:
        __version__ = "0.0.0-dev"
